
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rapid-auto-app
    container_name: rapid_auto
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
    networks:
      - rapid_auto

  web:
    image: nginx:stable-alpine
    container_name: rapid_auto_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - rapid_auto

  db:
    image: mysql:8.0
    container_name: rapid_auto_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rapid_auto
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: rapid_auto
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rapid_auto

networks:
  rapid_auto:

volumes:
  mysql_data:
